### ISSUE TITLE
change mobile phone numbers to not be real

### ISSUE THREAD

**Issue by mmicuta** [bvn-architecture/styleguide#104]
Under the "Stationery" section, mobile phone numbers for 3 different staff members are visible on the business cards. Just wanted to check that this information was intended to be published to the broader public, outside of people who have intentionally been given the business card?

**Comment by notionparallax** [comment]
Good point, let's mix them up a bit

**Comment by tuksun** [comment]
Should we also rename the people aswell with generic placeholder names eg. John Doe

**Comment by notionparallax** [comment]
I think that leaving the names real is fine!

**Comment by notionparallax** [comment]
@mmicuta thanks for pulling up this issue! Any more thoughts?
