### ISSUE TITLE
Fix "if key is larger than value, allign"

### ISSUE THREAD

**Issue by tuksun** [bvn-architecture/styleguide#122]

**Comment by notionparallax** [comment]
What does this mean?

**Comment by tuksun** [comment]
If left column is larger than right on the same level it wont align properlly and break itself

**Comment by notionparallax** [comment]
@tuksun it might be a good fit for flexbox too?

**Comment by tuksun** [comment]
I already solved it by adding "  float: left;   clear: left;" but ill have another look later
