### ISSUE TITLE
Add red text option

### ISSUE THREAD

**Issue by tuksun** [bvn-architecture/styleguide#127]
either:
-Make seperate div tag
-change H6 to normal font + red

**Comment by notionparallax** [comment]
Just add a `.red` class where the scss is:

`.red{color:red}`

Then you can say <h6 class="red"> or <p class="red">

**Comment by notionparallax** [comment]
@tuksun, this is me being pedantic, and contradicting what I said before:
If the red is presentational, then it should be called `.my-great-highlight` or `.extra-attention` or `.colour-highlight` 
That way you Can change your mind and not need to change the HTML. All the presentation is held in the CSS.

Nerd out over

**Comment by tuksun** [comment]
noooooooooooooooooooooooooooooooooooooooooooo

I'll leave it at the bottom, and double check a name afterwards. its not major atm

**Comment by notionparallax** [comment]
Not major at all. Just another one of those habits to cultivate
