### ISSUE TITLE
Fix block letter: Double check with all letters at the end

### ISSUE THREAD

**Issue by tuksun** [bvn-architecture/styleguide#130]
Reload into illustrator and check Blender font sizes for all letters

**Comment by notionparallax** [comment]
I'm still not convinced this needs to be svg.
I prefer svg to js, but are we satisfied that plain ole CSS won't cut it?

**Comment by tuksun** [comment]
ATM its one SVG controlled the chosen letter with an 'include', however when trying to scale the text, there is a large white gap on top that aligns the letter in the bottom left corner

**Comment by tuksun** [comment]
Originally tried to do it via css but couldnt get around it

**Comment by notionparallax** [comment]
Can you post some screen shots? Maybe a sketch of what's supposed to happen?

**Comment by tuksun** [comment]
Q is larger in height, else the height requirement isnt needed in css
