### ISSUE TITLE
reuse BVN logo as an external use tag

### ISSUE THREAD

**Issue by notionparallax** [bvn-architecture/styleguide#28]
As documented here: https://css-tricks.com/svg-use-with-external-reference-take-2/

https://github.com/jonathantneal/svg4everybody

would drop page weight quite a lot.

**Comment by notionparallax** [comment]
As documented here: https://css-tricks.com/svg-use-with-external-reference-take-2/

https://github.com/jonathantneal/svg4everybody

**Comment by tuksun** [comment]
Cant get it to work

**Comment by notionparallax** [comment]
There is a bug that means that it only works same origin.

That also means that it won't work locally.

https://lists.w3.org/Archives/Public/www-svg/2015Mar/0139.html
https://codereview.chromium.org/1036323002

major pain. close and maybe reopen in a year or so!

**Comment by notionparallax** [comment]
<svg>
  <use xlink:href="/styleguide/assets/test_file.svg#logo"></use>
</svg>

this kind of works, but it's hard work
