### ISSUE TITLE
As a contributor I'd like to be able to replicate the dev environment so that I can make a pull request

### ISSUE THREAD

**Issue by notionparallax** [bvn-architecture/styleguide#50]

**Comment by tuksun** [comment]
Currently have issues with "gem rdiscount"

**Comment by notionparallax** [comment]
What's the error?

**Comment by tuksun** [comment]
Seems to freeze when attempting to install "rdiscount" manually and with bundler. Attempts around it pop up with errors missing their native extentions. I cant remember how i fixed it
