### ISSUE TITLE
Make a proper "favicon"

### ISSUE THREAD

**Issue by tuksun** [bvn-architecture/styleguide#62]

**Comment by tuksun** [comment]
Run though: http://realfavicongenerator.net/

**Comment by notionparallax** [comment]
@tuksun Favicons seem to be working for me now. Should this be closed?

**Comment by tuksun** [comment]
This is more of a notice before launch that we need a proper icon

**Comment by notionparallax** [comment]
Lets consider the black square to be fine for now and close this issue
