### ISSUE TITLE
Polish up the meta tags

### ISSUE THREAD

**Issue by notionparallax** [bvn-architecture/styleguide#64]
Have a read of this:
https://moz.com/blog/meta-data-templates-123

Then use the testing tools to fill in the details in the _includes/head.html file

maybe also take all the social meta out into it's own included file too.

**Comment by tuksun** [comment]
https://developers.facebook.com/docs/platforminsights/domains

Use on account create the facebook page.

**Comment by notionparallax** [comment]
Hey, lets go through this together when you get back in.

**Comment by tuksun** [comment]
Main page has trouble loading meta data
